dashboard:
  port: 8060
  enabled: false
  host: my.host.name
  replicas: 1
  databaseName: mydatabase
  collectionName: mycollection
  permittedIngresses:
    - protocol: "*"
      source_cidr_block: "1.1.1.1/32"
  image:
    repository: iguaziodocker/provazio-dashboard
    tag: 0.0.1
    pullPolicy: IfNotPresent

  # holds cloud credentials
  secretName: zandbox-creds

  provisioner:
    env: dev
    type: aws
    region: us-east-1
    domain: my.domain.com

  internalNetworkCIDR: 1.1.1.1/32
  expirationCheckIntervalSeconds: 300

controller:
  enabled: false
  crd:
    create: true
    kinds:
    - Tenant
    - TenantAppServiceSet
  image:
    repository: iguaziodocker/provazio-controller
    tag: 0.0.1
    pullPolicy: IfNotPresent
