
logger:
  severity: info

image:
  repository: iguaziodocker/v3io_dayman
  tag: b1372_20180513080600
  pullPolicy: IfNotPresent

user: iguazio
resources:
  cpu: 1
  memory: "3Gi"
  numHugePages: 3000
  numOfWorkers: 1
  boostSizeInBytes: 10000000
  heaps: |
    {
      "kind": "mempool",
      "block_size_bytes": 4096,
      "num_blocks": 10000
    },
    {
      "kind": "mempool",
      "block_size_bytes": 9296,
      "num_blocks": 10000
    },
    {
      "kind": "mempool",
      "block_size_bytes": 16384,
      "num_blocks": 10000
    },
    {
      "kind": "mempool",
      "block_size_bytes": 1228800,
      "num_blocks": 500
    },
    {
      "kind": "mempool",
      "block_size_bytes": 2228800,
      "num_blocks": 200
    }

cdiPort: 1967
maxInFlightRequests: 1024
maxChannelInactivitySeconds: 180

datanode:
  uri: "tcp://localhost:1234"
