v3ioClient:
  image:
    repository: pavius/v3io_dayman_client
    tag: 1.7_b2_20180620143303
    pullPolicy: IfNotPresent

v3iod:
  logger:
    severity: info

  image:
    repository: iguaziodocker/v3io_dayman
    tag: 1.7_b2_20180620143303
    pullPolicy: IfNotPresent

  user: iguazio
  resources: {}
    # limits:
      # cpu: 1
      # memory: "3Gi"
    # requests:
      # cpu: 1
      # memory: "3Gi"
    
  cdiPort: 1967
  maxInFlightRequests: 1024
  maxChannelInactivitySeconds: 180
  numHugePages: 3000
  numOfWorkers: 1
  boostSizeInBytes: 10000000
  heaps: |
    {
      "kind": "mempool",
      "block_size_bytes": 4096,
      "num_blocks": 10000
    },
    {
      "kind": "mempool",
      "block_size_bytes": 9296,
      "num_blocks": 10000
    },
    {
      "kind": "mempool",
      "block_size_bytes": 16384,
      "num_blocks": 10000
    },
    {
      "kind": "mempool",
      "block_size_bytes": 1228800,
      "num_blocks": 500
    },
    {
      "kind": "mempool",
      "block_size_bytes": 2228800,
      "num_blocks": 200
    }

  datanode:
    uri: "tcp://localhost:1234"
