apiVersion: nuclio.io/v1beta1
kind: Function
metadata:
  name: {{ .Values.functions.query.name }}
  labels:
    nuclio.io/project-name: {{ .Values.project.name }} 
    app: {{ template "tsdb-functions.name" . }}
    chart: {{ template "tsdb-functions.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  build:
    codeEntryType: image
  handler: main:Handler
  image: {{ .Values.functions.query.image.repository }}:{{ .Values.functions.query.image.tag }}
  replicas: {{ .Values.functions.query.replicas }}
  runtime: golang
  env:
  - name: QUERY_V3IO_TSDB_PATH
    value: {{ .Values.tsdb.path }}
  triggers:
    web:
      kind: http
      attributes:
        port: {{ .Values.functions.query.port }}
  dataBindings:
    db0:
      kind: v3io
      url: {{ .Values.webapi.url | quote }}
      secret: {{ .Values.webapi.auth.username }}:{{ .Values.webapi.auth.password }}
status:
  state: waitingForResourceConfiguration
