{{- if and (.Values.controller.enabled) (has "Tenant" .Values.controller.crd.kinds) }}

# If the controller is enabled and responsible for Tenant, bind to the cluster-admin role 
# allowing it to do anything on the cluster

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "provazio.controller.name" . }}-tenant
  labels:
    app: {{ template "provazio.name" . }}
    chart: {{ template "provazio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: controller
subjects:
- kind: ServiceAccount
  name: {{ template "provazio.controller.name" . }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

{{- end }}
