{{- if .Values.controller.enabled }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "provazio.controller.name" . }}
  labels:
    app: {{ template "provazio.name" . }}
    chart: {{ template "provazio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: controller

{{- end }}