{{- if and .Values.controller.enabled .Values.controller.artifactVersionManifestContents }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "provazio.controller.name" . }}-artifact-version-manifest
  labels:
    app: {{ template "provazio.name" . }}
    chart: {{ template "provazio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: controller
data:
  artifactVersionManifest.json: |
    {{ .Values.controller.artifactVersionManifestContents | quote }}

{{- end }}
