{{- if .Values.controller.crd.create }}

# Create a ClusterRole that allows access to the Tenant CRD.
# This should be used by the system-level controller

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ template "controller.name" . }}-tenant
  labels:
    app: {{ template "controller.name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups: ["iguazio.com"]
  resources: ["tenant"]
  verbs: ["*"]

---

# Create a ClusterRole that allows access to the TenantAppServiceSet CRD.
# This should be used by the tenant-level controller

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ template "controller.name" . }}-tenantappserviceset
  labels:
    app: {{ template "controller.name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups: ["iguazio.com"]
  resources: ["tenantappserviceset"]
  verbs: ["*"]

{{- end }}
