{{- if and (.Values.controller.enabled) (has "TenantAppServiceSet" .Values.controller.crd.kinds) }}

# If the controller is enabled and responsible for TenantAppServiceSet, it will need the ability
# to create resources like ingressess, secrets, etc. Things that are not created by the service
# helm charts which are under the namespace's tiller service account. This binds the service
# account to the role allowing this

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "provazio.controller.name" . }}-tenantappserviceset-role
  labels:
    app: {{ template "provazio.controller.name" . }}
    chart: {{ template "provazio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: {{ template "provazio.controller.name" . }}
roleRef:
  kind: Role
  name: {{ template "provazio.controller.name" . }}-tenantappserviceset
  apiGroup: rbac.authorization.k8s.io

{{- end }}
