{{- if and (.Values.controller.enabled) (has "TenantAppServiceSet" .Values.controller.crd.kinds) }}

# If the controller is enabled and responsible for TenantAppServiceSet, it will need the ability
# to create resources like ingressess, secrets, etc. Things that are not created by the service
# helm charts which are under the namespace's tiller service account. This creates a role
# granting namespaced permission to these resources

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: provazio-controller-crd-tenantappserviceset
  labels:
    app: {{ template "provazio.name" . }}
    chart: {{ template "provazio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: controller
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

{{- end }}
