{{- if .Values.controller.enabled }}

{{- if has "TenantAppServiceSet" .Values.controller.crd.kinds }}

# If the controller is responsible for TenantAppServiceSet, bind to the cluster role that allows access
# to the CRD. Since this controller will be creating/updating/deleting services, it will also need access
# to several resources

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "controller.name" . }}-tenantappserviceset-cluserrole
  labels:
    app: {{ template "controller.name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: {{ template "controller.name" . }}
roleRef:
  kind: ClusterRole
  name: {{ template "controller.name" . }}-tenantappserviceset
  apiGroup: rbac.authorization.k8s.io

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "controller.name" . }}-tenantappserviceset
  labels:
    app: {{ template "controller.name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "controller.name" . }}-tenantappserviceset-role
  labels:
    app: {{ template "controller.name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: {{ template "controller.name" . }}
roleRef:
  kind: Role
  name: {{ template "controller.name" . }}-tenantappserviceset
  apiGroup: rbac.authorization.k8s.io

---
{{- end }}

{{- if has "Tenant" .Values.controller.crd.kinds }}

# If the controller is responsible for Tenant, bind to the cluster role allowing access to tenants

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "controller.name" . }}-tenant
  labels:
    app: {{ template "controller.name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: {{ template "controller.name" . }}
roleRef:
  kind: ClusterRole
  name: {{ template "controller.name" . }}-tenant
  apiGroup: rbac.authorization.k8s.io

---
{{- end }}
{{- end }}

