{{- if .Values.controller.crd.create }}

apiVersion: apiextensions.k8s.io/v1beta1
description: Tenant resource
kind: CustomResourceDefinition
metadata:
  name: tenants.iguazio.com
  labels:
    chart: {{ template "provazio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  group: iguazio.com
  names:
    kind: Tenant
    plural: tenants
    singular: tenant
  scope: Namespaced
  version: v1beta1

{{- end }}
