{{- if .Values.vault.enabled }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "provazio.vault.name" . }}
  labels:
    app: {{ template "provazio.name" . }}
    chart: {{ template "provazio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: vault

{{- end }}
