apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "daemon-name" . }}
data:
  init.sh: |
    #!/usr/bin/env bash
    set -e
    chown -R {{ .Values.user }}:{{ .Values.user }} /tmp
    ulimit -S -H -l unlimited
    echo {{ .Values.resources.numHugePages }} > /proc/sys/vm/nr_hugepages
    su --preserve-environment \
      --login {{ .Values.user }} \
      --command "/usr/local/bin/v3io_dayman --config-path /etc/iguazio/dayman/default.json"

  default.json: |
    {
      "num_workers": {{ default 1 .Values.resources.numOfWorkers }},
      "max_channel_inactivity_period_seconds": {{ .Values.maxChannelInactivitySeconds }},
      "max_inflight_requests": {{ .Values.maxInFlightRequests }},
      "cdi": {
        "listen_addr": "0.0.0.0:{{ .Values.cdiPort }}"
      },
      "job_block_allocator": {
        "mode": "per-worker",
        "heaps": [
{{ .Values.resources.heaps | indent 10 }}
{{- if .Values.resources.boostSizeInBytes -}}
          ,{
            "kind": "boost",
            "size_bytes": {{ printf "%d" (int .Values.resources.boostSizeInBytes) }}
          }
{{- end }}
        ]
      },
      "logger": {
        "mode": "direct",
        "severity": "{{ .Values.logger.severity }}",
        "path": "/var/log/iguazio"
      },
      "paths": {
        "fifo": "/tmp/dayman",
        "uds": "/tmp/dayman",
        "pidfile": "/tmp/dayman.pid"
      },
      "cluster": {
        "uri": {{ .Values.datanode.uri | quote }}
      }
    }
