master:
  image:
    repository: "iguaziodocker/spark"
    tag: "2.1.2-1.5.2"
    pullPolicy: "IfNotPresent"
  replicas: 1
  servicePort: 7077
  containerPort: 7077
  
  resources: {}
    # limits:
      # cpu: 1
      # memory: "3Gi"
    # requests:
      # cpu: 1
      # memory: "3Gi"
  
  webAdmin:
    servicePort: 8080
    containerPort: 8080

worker:
  image:
    repository: "iguaziodocker/spark"
    tag: "2.1.2-1.5.2"
    pullPolicy: "IfNotPresent"
  replicas: 1
  containerPort: 8081
  executorMemory: "1g"
  
  resources: {}
    # limits:
      # cpu: 1
      # memory: "4Gi"
    # requests:
      # cpu: 1
      # memory: "4Gi"

zeppelin:
  image:
    repository: "iguaziodocker/zeppelin"
    tag: "0.7.3-1.5.2"
    pullPolicy: "IfNotPresent"
  replicas: 1
  servicePort: 8080
  containerPort: 8080
  # nodePort: 32100
  
  resources: {}
    # limits:
      # cpu: 1
      # memory: "2Gi"
    # requests:
      # cpu: 1
      # memory: "2Gi"

  preloadNotebooks:
    enabled: true
    notebooks: {}

v3io:
  auth:
    password: "password"
    tenant: "Default"
  lookupService:
    name: "v3iod-registry"
    servicePort: 8080
    path: "registry/v3iod"
