apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "zeppelin-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: zeppelin
spec:
  replicas: {{ .Values.zeppelin.replicas }}
  strategy:
    type: "RollingUpdate"
  selector:
    matchLabels:
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      component: "zeppelin"
  template:
    metadata:
      labels:
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        component: "zeppelin"
    spec:
      containers:
        - name: {{ template "zeppelin-fullname" . }}
          image: "{{ .Values.zeppelin.image.repository }}:{{ .Values.zeppelin.image.tag }}"
          imagePullPolicy: {{ .Values.zeppelin.image.pullPolicy | quote }}
          command: ["/bin/bash"]
          args:
            - /etc/run/init.sh
          ports:
            - containerPort: {{ .Values.zeppelin.containerPort }}
          resources:
            requests:
              cpu: {{ .Values.zeppelin.resources.cpu }}
              memory: {{ .Values.zeppelin.resources.memory | quote }}
            limits:
              cpu: {{ .Values.zeppelin.resources.cpu }}
              memory: {{ .Values.zeppelin.resources.memory | quote }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.zeppelin.containerPort }}
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.zeppelin.containerPort }}
            initialDelaySeconds: 90
          env:
            - name: MASTER
              value: "spark://{{ template "master-fullname" . }}:{{ .Values.master.servicePort }}"
            - name: IGZ_DATA_CONFIG_FILE
              value: "/tmp/v3io.conf"
            - name: CURRENT_NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          volumeMounts:
            - mountPath: "/etc/config"
              name: "config-volume"
            - mountPath: "/etc/run"
              name: "init-volume"
            - mountPath: "/dev/shm"
              name: "shm"
            - mountPath: "/tmp/dayman"
              name: "daemon-comm"
{{- if .Values.zeppelin.preloadNotebooks.enabled }}
            - mountPath: "/tmp/notebooks"
              name: "notebook-volume"
{{- end }}        
      volumes:
          - name: "config-volume"
            configMap:
              name: "{{ .Release.Name }}-spark"
          - name: "init-volume"
            configMap:
              name: {{ template "zeppelin-fullname" . }}
          - name: "shm"
            hostPath:
              path: "/dev/shm"
          - name: "daemon-comm"
            hostPath:
              path: "/tmp/dayman"
{{- if .Values.zeppelin.preloadNotebooks.enabled }}
          - name: "notebook-volume"
            configMap:
              name: {{ template "zeppelin-fullname" . }}-notebooks
{{- end }}              
