apiVersion: v1
kind: Service
metadata:
  name: {{ template "webui-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "spark-master"
spec:
  ports:
    - port: {{ .Values.master.webAdmin.servicePort }}
      targetPort: {{ .Values.master.webAdmin.containerPort }}
  selector:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "spark-master"
