apiVersion: v1
kind: Service
metadata:
  name: {{ template "master-name" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: spark-master
spec:
  ports:
    - port: {{ .Values.master.servicePort }}
      targetPort: {{ .Values.master.containerPort }}
  selector:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: spark-master
