apiVersion: nuclio.io/v1beta1
kind: Function
metadata:
  name: {{ template "netopsDemo.generateName" . }}
  labels:
    app: {{ template "netopsDemo.name" . }}
    chart: {{ template "netopsDemo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    nuclio.io/project-name: {{ template "netopsDemo.projectName" . }}
spec:
  build:
    codeEntryType: image
  env:
  - name: GENERATOR_CONFIGURATION
    valueFrom:
      configMapKeyRef:
        name: {{ template "netopsDemo.generateName" . }}-config
        key: configuration.json
  handler: functions.generate.generate:generate
  image: {{ .Values.generate.image.repository }}:{{ .Values.generate.image.tag }}
  replicas: 1
  runtime: python:3.6
  triggers:
    periodic:
      kind: cron
      workerAllocatorName: defaultHTTPWorkerAllocator
      attributes:
        interval: 1s
status:
  state: waitingForResourceConfiguration
