apiVersion: nuclio.io/v1beta1
kind: Function
metadata:
  name: {{ template "netopsDemo.ingestName" . }}
  labels:
    app: {{ template "netopsDemo.name" . }}
    chart: {{ template "netopsDemo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    nuclio.io/project-name: {{ template "netopsDemo.projectName" . }}
spec:
  build:
    codeEntryType: image
  handler: main:Ingest
  image: {{ .Values.ingest.image.repository }}:{{ .Values.ingest.image.tag }}
  replicas: 1
  runtime: golang
  env:
{{- if .Values.ingest.tsdb.enabled }}
  - name: INGEST_V3IO_TSDB_PATH
    value: {{ .Values.ingest.tsdb.path }}
{{- end }}
{{- if .Values.ingest.anodot.enabled }}
  - name: INGEST_ANODOT_URL
    value: {{ .Values.ingest.anodot.url }}
  - name: INGEST_ANODOT_TOKEN
    value: {{ .Values.ingest.anodot.token }}
{{- end }}
{{- if .Values.ingest.tsdb.enabled }}
  dataBindings:
    db0:
      class: v3io
      secret: {{ .Values.ingest.tsdb.username }}:{{ .Values.ingest.tsdb.password }}
      url: {{ .Values.ingest.tsdb.url | quote }} 
{{- end }}
status:
  state: waitingForResourceConfiguration
