apiVersion: nuclio.io/v1beta1
kind: Project
metadata:
  name: {{ template "netops-demo.projectName" . }}
  labels:
    app: {{ template "netops-demo.name" . }}
    chart: {{ template "netops-demo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  displayName: {{ .Values.project.displayName }}
